import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { Col, Divider, Row } from "antd";
import Databox from "../Components/Databox";
// import { gql, useQuery } from "@apollo/client";
import { useQuery, gql } from "@apollo/client";
const GET_LOCATIONS = gql`
  query MyQuery {
    check_in {
      id
      comment
      created_at
      image_url
      name
      updated_at
    }
  }
`;
export default function Home() {
  const { isSuccess, loading, error, data } = useQuery(GET_LOCATIONS);
  console.log(data, loading);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Row
        gutter={[0, 10]}
        style={{
          paddingTop: "2rem",
          paddingBottom: "2rem",
          borderBottom: "1px solid #F0F0F0",
        }}
      >
        <Col span={24}>
          <p
            style={{
              fontFamily: "Roboto",
              fontSize: "30px",
              fontWeight: "500",
              lineHeight: "40px",
              textAlign: "center",
            }}
          >
            CheckIns
          </p>
        </Col>
        <Col span={24}>
          <p
            style={{
              fontFamily: "Roboto",
              fontSize: "14px",
              fontWeight: "500",
              lineHeight: "22px",
              textAlign: "center",
            }}
          >
            See all the checkins below, click on one, and edit it
          </p>
        </Col>
      </Row>
      <Row
        gutter={[16, 16]}
        style={{
          backgroundColor: "#F0F0F0",
          paddingLeft: "5rem",
          paddingRight: "5rem",
          paddingTop: "2rem",
          paddingBottom: "2rem",
        }}
      >
        {loading == false &&
          data?.check_in.map((s) => {
            return (
              <Col span={8}>
                <Databox data={s} />
                
              </Col>
            );
          })}
        
      </Row>
    </>
  );
}
